# 陣列 (Array)

陣列的介紹包含了一維到多維陣列，通常一維陣列也稱為向量 (vector)，二維陣列稱為矩陣 (matrix)。有關於陣列相關的父型別，最主要是由 `AbstractArray`、`AbstractVector`、`AbstractMatrix` 組成，分別可以用來代表 N 維、一維、二維的陣列的抽象型別。

![](./AbstractArray.png)

[註1] 在多維陣列提到索引或元素的位置時，我們將採用”直”行(column) ”橫”列(row) 來表示。

[註2] 型別系統將會在後續的內容中進行詳細介紹。

## 1. 陣列的建立

最簡單的 array 創建方式，用中括號 `[ ]` 包含所有陣列元素 (element)。

In [1]:
A = [1 5 3]

1×3 Array{Int64,2}:
 1  5  3

陣列中的元素可以具備不同的資料型別值。可以讓 Julia 自動識別元素類型而不指定，而 Julia 回傳的型別則會是 `Any`。

In [2]:
A = [1.0 "a string" 3]

1×3 Array{Any,2}:
 1.0  "a string"  3

使用 `fill()` 函式也可以產生陣列。下例是產生一個 2 x 3 的陣列，陣列內的值均為數字 1。

In [3]:
fill(1, (2, 3))

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

若是要值填入一個既有的陣列，可以使用 `fill!()` 函式。

In [4]:
a = zeros(2, 3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [5]:
fill!(a, 3)

2×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0

若要查看陣列的維度，可以使用 `ndims()` 函式回傳陣列的維度數。要注意的是，列陣列的維度也會是 2。

In [13]:
A = [1 5 3]

1×3 Array{Int64,2}:
 1  5  3

In [14]:
ndims(A)

2

行陣列 (或稱行向量) 的維度則會是 1。

In [15]:
a = [1, 5, 3]
ndims(a)

1

在創建行陣列 (或稱行向量) 時可以用逗號或分號換列，但是在創建二維陣列 (矩陣) 時則不能用逗號換列，所以建議可以統一用分號，就不會混淆了。

In [24]:
A = [1 2; 3 4; 5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

用逗號則會產生錯誤。

In [25]:
A = [1 2, 3 4, 5 6]

LoadError: syntax: unexpected comma in matrix expression

### 向量 (Vector) 與矩陣 (Matrix)

如同一開始所提，向量和矩陣分別是一維和二維的陣列，在 Julia 中也提供了 `Vector` 和 `Matrix` 別名 (alias)。

In [26]:
Vector

Array{T,1} where T

In [29]:
Vector{Float64}(undef, 3)

3-element Array{Float64,1}:
 1.1438328e-315
 3.66986262e-315
 3.6698627e-315

In [30]:
Matrix

Array{T,2} where T

### 指定陣列元素的型別

創建陣列時，可以讓 Julia 自動識別元素型別而不指定。要指定型別的話，在陣列前面加上型別即可。

In [31]:
Float32[1, 2, 3, 4]

4-element Array{Float32,1}:
 1.0
 2.0
 3.0
 4.0

如果指定的類型無法被精確轉型時 (例如欲將浮點轉為整數)，系統會拋出 error。

In [32]:
Int32[1.1 2 3]

InexactError: InexactError: Int32(1.1)

### 常用函式建立並初始化陣列中的元素

下列為常用的函式，可以用來建立陣列並初始化陣列中的元素。

|函式|描述|
|--|--|
|zeros()|陣列元素初始化為 0|
|ones()|陣列元素初始化為 1|
|trues()|陣列元素初始化為 true 的 BitArray 類型|
|falses()|陣列元素初始化為 false 的 BitArray 類型|
|rand()|產生元素為隨機介於 \[0, 1 區間的均勻分布數字|
|randn()|產生元素為隨機常態分布的數字|

In [41]:
zeros((2,3))

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [42]:
ones((2,3))

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [43]:
trues((2,3))

2×3 BitArray{2}:
 1  1  1
 1  1  1

In [44]:
falses((2,3))

2×3 BitArray{2}:
 0  0  0
 0  0  0

In [45]:
rand(Float32, 3, 2)

3×2 Array{Float32,2}:
 0.494012  0.0943459
 0.720791  0.259137
 0.319986  0.917191

In [46]:
randn(3, 2)

3×2 Array{Float64,2}:
  0.95745  -0.301693
  1.27176  -0.0106582
 -2.66861  -0.89201

### 使用 `collect()` 函式建立陣列 

使用 `collect()` 函式來建立陣列。在下列範例中並搭配 `reshape()` 函式，改變陣列維度以建立多維陣列。

In [47]:
# 建立一維陣列，起始值為 1，數值間隔 2，結束值 10
collect(1:2:10)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [48]:
# 建立 5x2 陣列
reshape(collect(1:1:10), (5, 2))

5×2 Array{Int64,2}:
 1   6
 2   7
 3   8
 4   9
 5  10

## 2. 陣列的相關操作

### 索引

透過索引取得陣列元素值，有**線性索引**和**笛卡兒索引**兩種方式。

需特別留意的是，Julia 的索引值起始是 1 而非 0，和多數程式語言不同。

In [49]:
A = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

4×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

線性索引的順序如圖，所以在下列範例中 A[7] 會得到 A[3, 2] 的值。

![](./scalar_index.png)

In [50]:
# 線性索引，得到 A[3, 2] 的值
A[7]

8

笛卡兒索引是用 `A[<<row index>>, <<column index>>]` 的方式，取得該位置的值。

In [51]:
# 笛卡兒索引
A[3, 2]

8

索引也可以使用範圍 (range) 來指定。

In [52]:
A[1, 1:2]

2-element Array{Int64,1}:
 1
 2

使用 `getindex()` 也可以取得該索引位置的值。

In [54]:
getindex(A, 3, 2)

8

###  遍歷 (Traversal)

In [62]:
# 使用笛卡兒索引將陣列中所有元素印出
A = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

for i = 1:size(A, 1), j = 1:size(A, 2)
    print(A[i, j], " ")
end

1 2 3 4 5 6 7 8 9 10 11 12 

In [64]:
# 使用線性索引將陣列中所有元素印出
for i = 1:lastindex(A)
    print(A[i], " ")
end

1 4 7 10 2 5 8 11 3 6 9 12 

In [66]:
# 用迭代的方式將陣列中所有元素印出
# 也可以用 in 取代 ∈
for x ∈ A
    print(x, " ")
end

1 4 7 10 2 5 8 11 3 6 9 12 

### 加入或剔除陣列的元素 (Push & Pop)

要加入或加入或剔除陣列的元素，可以透過下列函式：

|函式|說明|
|---|---|
|push!()|加入元素到陣列的尾端|
|pushfirst!()|加入元素到陣列成為第一個元素|
|pop!()|將陣列的最後一個元素剔除|
|popfirst!()|將陣列的第一個元素剔除|

以上函式都會直接變更原陣列。

In [67]:
A = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [68]:
push!(A, 6)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [ ]:
pushfirst!(A, 0)

7-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5
 6

In [69]:
pop!(A)
A

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [70]:
popfirst!(A)
A

4-element Array{Int64,1}:
 2
 3
 4
 5

### 陣列的組合

若陣列中含有陣列 (或稱巢狀陣列)，Julia 會自動依維度展開。

In [71]:
[1 2 [3 4]]

1×4 Array{Int64,2}:
 1  2  3  4

巢狀內外陣列維度不相同會產生 error。

In [72]:
[1; 2 [3; 4]]

DimensionMismatch: DimensionMismatch("mismatch in dimension 1 (expected 1 got 2)")

陣列組合的背後，其實是呼叫了 `cat()`、`vcat()`、`hcat()`、或 `hvcat()` 函式。使用範例如下：

In [73]:
W = [1 2]
X = [3 4]
Z = [5 6]

# 合併陣列為列向量
cat(W, X, Z, dims=2)

1×6 Array{Int64,2}:
 1  2  3  4  5  6

In [75]:
W = [1 2]
X = [3 4]
Z = [5 6]

# 依"行"合併陣列
# 此範例合併陣列為列向量
hcat(W, X, Z)

1×6 Array{Int64,2}:
 1  2  3  4  5  6

In [76]:
# 依"列"合併陣列
# 等同於cat(W, X, Z, dims=1)
vcat(W, X, Z)

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [77]:
# 依照指定每列的行數合併數值成為陣列
D = hvcat((3, 3), 1, 2, 3, 4, 5, 6)

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

### 切片(Slicing)和視圖(View)

#### 切片

陣列切片，也就是將陣列中的子陣列擷取出來；使用 `view()` 函式可以產生陣列的視圖，擷取出來的視圖，其型別為 `SubArray`。

在效能表現上，視圖會比切片快很多。

In [78]:
A = reshape(collect(1:15), 3, 5)

3×5 Array{Int64,2}:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [79]:
# 使用笛卡兒索引切片
A[1, 2]

4

In [80]:
# 使用範圍取得子陣列
A[2, 2:end]

4-element Array{Int64,1}:
  5
  8
 11
 14

使用條件式切片回傳的將會是一維陣列。

In [81]:
A[A .> 8]

7-element Array{Int64,1}:
  9
 10
 11
 12
 13
 14
 15

#### 視圖

In [87]:
b = view(A, 2:3, 2:3)

2×2 view(::Array{Int64,2}, 2:3, 2:3) with eltype Int64:
 5  8
 6  9

視圖也可以透過跟陣列一樣的方式進行操作，但是特別要留意的是，視圖中的元素值被改變時，原始陣列對應的元素值也會被改變。

In [88]:
b[1, 1] = 100

100

In [89]:
A

3×5 Array{Int64,2}:
 1    4  7  10  13
 2  100  8  11  14
 3    6  9  12  15

## 3. 點運算 (Vectorized Operation)

陣列對點運算的支援提供了很方便的機制，來進行對陣列中元素的處理和操作，而不需要再用遍歷的方式 (例如：迴圈) 來操作陣列。下面的範例是透過點運算，將陣列中的每個元素進行 `round()` (IEEE 754 捨入)、加法、及三次方的語法示範。

### 點運算適用的運算子 (operator)

||運算子|
|---|---|
|一元運算子|-, +|
|二元運算子|-, +, *, /, \\, ^|
|比較運算子|==, !=, ≈ (isapprox), ≉|

In [90]:
[1, 2, 3] .^ 3

3-element Array{Int64,1}:
  1
  8
 27

### Broadcasting

In [91]:
A = [1.1, 2.2, 3.5]
broadcast(+, A, 2)

3-element Array{Float64,1}:
 3.1
 4.2
 5.5

若不使用 broadcast 與加法的話，下列程式也可以得到相同的結果。

In [94]:
function f(x)
    x += 2
end

map(f, A)

3-element Array{Float64,1}:
 3.1
 4.2
 5.5

## 4. 排序 (Sort)

預設的 Sort 是 QuickSort，排序是以由小到大排序。

`sort()` 在排序後不會改變原來陣列的元素值順序，如果要改變的話，可以呼叫 `sort!()`。

In [95]:
sort([2, 1, 4, 3, 5])

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

若要反序排序 (由大到小)，可以加上 `rev=true` 參數。

In [96]:
sort([2, 1, 4, 3, 5], rev=true)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

在排序時可以同時進行轉換，例如依據 `abs` 絕對值排序，不過如下面範例所示，`by` 並不會改變原本陣列的元素值，但是排序會依轉換後的值做排序。

如果陣列裡面的元素是其他集合型別，例如是 Tuple、Pair、Dictionary 的話，也可以用 `by` 來指定排序依據。在介紹到其他集合型別時會有更多範例說明。

In [97]:
sort([-2, 1, -4, 3, -5], by=abs, rev=true)

5-element Array{Int64,1}:
 -5
 -4
  3
 -2
  1

對於多維陣列，排序時必須指定 `dims` 參數，指定排序旳維度，否則會產生錯誤。

In [98]:
A = [2 1 3; 4 5 6; 1 3 5]

3×3 Array{Int64,2}:
 2  1  3
 4  5  6
 1  3  5

下例是指定依照列 (row) 值排序。

In [103]:
sort(A, dims=1)

3×3 Array{Int64,2}:
 1  1  3
 2  3  5
 4  5  6

In [104]:
sort([2, 1, 4, 3, 5], alg=InsertionSort)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

Julia 內建支援幾種不同的排序演算法：

- InsertionSort
- QuickSort
- PartialQuickSort(k)
- MergeSort

有關於 QuickSort 排序演算法的使用範例如下。首先我們先用 `rand()` 隨機產生 100 個 1 到 500 之間的數字。在範例中也運用 `@time` 巨集來輸出各種不同排序的執行時間進行比較。

對於各種不同排序的詳細說明及比較，請見參考資料：[[演算法] 排序演算法(Sort Algorithm)](http://notepad.yehyeh.net/Content/Algorithm/Sort/Sort.php)

In [112]:
x = rand(1:100, 10)

10-element Array{Int64,1}:
 45
 49
 36
 20
 81
 43
 13
 57
  4
 60

In [126]:
@time s = sort(x, alg=QuickSort)

  0.000005 seconds (1 allocation: 160 bytes)


10-element Array{Int64,1}:
  4
 13
 20
 36
 43
 45
 49
 57
 60
 81

## 5. 搜尋 (Search)

搜尋某值是否存在於陣列中，可以用 `in`，回傳值為 true 或 false。

In [127]:
in(3, [1, 3, 5, 7, 9])

true

使用 `findall()` 函式，搜尋並回傳結果值的索引。

In [133]:
findall(in(1), [5, 3, 2, 1])

1-element Array{Int64,1}:
 4

使用 `findmax()` 及 `findmin()` 函式，回傳找到的最大值或最小值，及其索引值。

In [136]:
findmax([2, 3, 1, 5]) 

(5, 4)

In [138]:
findmin([2, 3, 1, 5]) 

(1, 3)

若是陣列已排序，可以使用 `searchsorted()`, `searchsortedfirst()`, `searchsortedlast()`，取得該值的索引值。

特別注意的是 `searchsorted()` 回傳的是索引值範圍 (range)。

In [139]:
searchsorted([1, 2, 3, 5], 1)

1:1

In [143]:
searchsortedfirst([1, 2, 3, 1], 1)

1

In [149]:
searchsortedlast([1, 2, 3, 1], 1)

1

若要判斷是否已排序，可以透過 `issorted()` 函式，`rev` 參數判斷是由小到大或是由大到小排序。

In [150]:
issorted([5, 3, 2, 1], rev=true)

true

## 6. 陣列常用函式範例

|函式|說明|
|---|---|
|eltype(A)|	陣列A中的元素類型。|
|length(A)|	陣列A中的元素總數，例如 3x2 的陣列其元素總數為 6。|
|ndims(A)	|陣列A的維度數，例如二維陣列維度數為2。|
|size(A)|	陣列A的維度，回傳值是 tuple 類型，例如 3x2 的陣列其回傳值為 (3, 2)。|
|eachindex(A)|	陣列A所有索引值。|
|lastindex(A)|	陣列A最後一個索引值。|
|axes(A)|	陣列A所有維度的有效索引值，回傳值是 tuple 類型。|
|strides(A)|	陣列A各維度在記憶體中的距離(元素數目) ，回傳值是 tuple 類型。|

In [151]:
A = [1 2; 3 4; 5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [152]:
eltype(A)

Int64

In [153]:
length(A)

6

In [154]:
ndims(A)

2

In [155]:
size(A)

(3, 2)

In [158]:
size(A, 2)

2

In [159]:
axes(A)

(Base.OneTo(3), Base.OneTo(2))

In [160]:
axes(A, 2)

Base.OneTo(2)

In [161]:
eachindex(A)

Base.OneTo(6)

In [162]:
lastindex(A)

6

In [163]:
strides(A) # a tuple of the strides in each dimension

(1, 3)

In [164]:
stride(A, 2) # the stride (linear index distance between adjacent elements) along dimension k

3